### ISSUE TITLE
Top5 Sample - Return on New Line not flowing through?

### ISSUE THREAD

**Issue by simongis** [Esri/arcade-expressions#11]
Looking at the [top 5 sample](https://github.com/Esri/arcade-expressions/blob/master/popup/top-five-list.md) for the purpose of a popup.

When I configure this with my own data and test the expression within the style editor, everything is looking good:

![image](https://user-images.githubusercontent.com/2769383/46912733-6fb31080-cfb0-11e8-813f-7864d2cec56f.png)

And I can see that the expression is honouring placing each result into a new line with _TextFormatting.NewLine_

However, over in the pop-up, this does not seem to be flowing through:

![image](https://user-images.githubusercontent.com/2769383/46912751-c3255e80-cfb0-11e8-8b60-f52ad18a06a1.png)

_As a Web Map author, I would like the NewLine to flow through to the popup so that my end users can more easily see the results._  

I can also see the same issue on [the referenced Web Map example
](https://jsapi.maps.arcgis.com/home/webmap/viewer.html?webmap=1add0bb044974d558f263ea468710aad)

**Comment by ekenes** [comment]
Yes. This is actually a JS API issue, not so much an Arcade one. I'll create the issue in our repo and see how we can solve this. I'll update this thread with new information as necessary.

**Comment by ekenes** [comment]
This has been installed in our 3.x dev branch. Will install in 4.x shortly. 

![screen shot 2018-11-02 at 2 41 43 pm](https://user-images.githubusercontent.com/11429922/47941963-78ab4980-dead-11e8-8c84-5196710ec857.png)

I'm going to consider this installed, then close after we release in a couple of months.

**Comment by simongis** [comment]
Excellent work!

**Comment by tforward** [comment]
> Yes. This is actually a JS API issue, not so much an Arcade one. I'll create the issue in our repo and see how we can solve this. I'll update this thread with new information as necessary.

What did you do to fix it? I noticed that also ArcGIS web maps in general don't work with newlines...

**Comment by ekenes** [comment]
Arcade doesn't return markup, only numbers or strings in the popup profile. So we had to interpret that constant as a `<br />` in this profile. The implementation is different for the labeling profile (we still don't have new lines in 3.x), but we do in 4.x - https://developers.arcgis.com/javascript/latest/sample-code/labels-multiline/index.html

**Comment by tforward** [comment]
Would it ever interpret a string as markup? The capabilities of having
markup for popups would be a game changer, in creating custom popups. I
find at the moment I have to write so many little expressions, basically
per field because can't output a completed popup in one arcade script.

At least when newlines are supported it would be possible to output dynamic
Multi-line popups, which is at least workable

**Comment by ekenes** [comment]
> At least when newlines are supported it would be possible to output dynamic
Multi-line popups, which is at least workable

Yes. That's why we want to at least get that out the door soon. But we are also looking at various options to make it more friendly to work with multiple values, permitting markup as a return type is one of them, but there are others on the table as well.

**Comment by tforward** [comment]
> > At least when newlines are supported it would be possible to output dynamic
> > Multi-line popups, which is at least workable
> 
> Yes. That's why we want to at least get that out the door soon. But we are also looking at various options to make it more friendly to work with multiple values, permitting markup as a return type is one of them, but there are others on the table as well.

That would be amazing! Its a stretch but CSS <style> tags over inline would be a big improvement,  

The current workflow to get a custom popup has so much overhead that it's not really worth doing, 

- Build out of all the HTML markup for each field and paste into the custom popup window under the view HTML source button.
- Use a CSS inliner tool to get the CSS in there
- Write out  each of the Arcade expressions individually, per field then write in your expressions into each spot needed in the HTML markup
- and repeat for every feature

**Comment by ekenes** [comment]
Closing this issue since newline functionality was installed in popups at 4.10/3.28.
