### ISSUE TITLE
Date Issue

### ISSUE THREAD

**Issue by simongis** [Esri/arcade-expressions#13]
Feel free to throw me back over to GeoNet.

I have an epoch beind updated on [my Hosted Feature Service.](https://services9.arcgis.com/M6PRFWHKXSvV72Qg/arcgis/rest/services/Public_Transport_Realtime_Vehicle_Positions/FeatureServer/0)

`APIdate (type: esriFieldTypeInteger, alias: API date (epoch), SQL Type: sqlTypeOther...`

If I apply a simple expression:

`Date($feature.APIdate)`

It returns the wrong year entirely.

![image](https://user-images.githubusercontent.com/2769383/48248715-727c1680-e433-11e8-8e67-ac1b559843dd.png)

However, if I check this epoch in an online tool, it converts correctly:

![image](https://user-images.githubusercontent.com/2769383/48248630-1e713200-e433-11e8-8f6d-ff4d864f6c6b.png)

Im sure this is an easy one - what am I missing in my expression?

What I really want to achieve, is how many minutes since last update.  

Something like this?
`DateDiff((Date($feature.APIdate)), Now(), minutes)`

**Comment by ekenes** [comment]
This looks like a difference between the meaning of "epoch" in UNIX versus JavaScript. What you're looking for is:

`Date($feature.APIdate * 1000)`

I tested with your example and it appears to work.

**Comment by simongis** [comment]
That works, thanks!
Keep getting 'finishSequenceExpression is not a function' when trying to work out the difference in minutes to now(), but will have a stab over the weekend.

Thanks again!

**Comment by simongis** [comment]
DateDiff(Now(), Date($feature.APIdate * 1000))  = Returns: _967671_

DateDiff(Now(), Date($feature.APIdate * 1000), minutes) = Returns: _Execution Error:Runtime Error: Identifier Not Found. minutes_

DateDiff(Now(), Now(), minutes) = Returns: _Execution Error:Runtime Error: Identifier Not Found. minutes_

var currentDateTime = Now()
var apiDateTime = Date($feature.APIdate * 1000)

Minute(DateDiff(currentDateTime, apiDateTime)) = _NaN_

DateDiff(minute, currentDateTime, apiDateTime) = _NaN_

**Comment by ekenes** [comment]
`DateDiff(Now(), Date($feature.APIdate * 1000), minutes)` returns an error because the value of the third parameter must be a string. You're passing `minutes` instead of `'minutes'`, so it treats `minutes` like an undeclared variable. 

Try the following and it should work: `DateDiff(Now(), Date($feature.APIdate * 1000), 'minutes')`

**Comment by simongis** [comment]
So close!  Thanks @ekenes

**Comment by simongis** [comment]
// *1000 because epoch in UNIX & Javascript differences
Round(DateDiff(Now(), Date($feature.APIdate * 1000), 'seconds'),0)
