### ISSUE TITLE
Fade symbols using TimeStamp, in relation to Map Time

### ISSUE THREAD

**Issue by simongis** [Esri/arcade-expressions#17]
Not having much luck [over on GeoNet](https://community.esri.com/thread/229773-fade-symbols-using-timestamp-in-relation-to-map-time), so figured this repo contributors could point me in the right direction.

- I have a point dataset with a single datetime field;
- I have enabled Time using this field;
- I have a time window of 1 day;
- The temporal extent of the dataset is one month

I want to come up with a renderer, that shows points that are at the front of the time window to be entirely solid. But at the back of the time window, I want them to be pretty much transparent. So a linear stretch of opacity for the time window. Easier to take look at this example:

![image](http://s3-ap-southeast-2.amazonaws.com/languagesofaustralia.com/public/download.gif)

However, the above sample is web, and I believe was achieved [using some JS ](https://github.com/maplabs/pulse/blob/master/code/js/main.js#L327)over Arcade 

**My question is how to best achieve this within ArcGIS Pro with Arcade?**

I am struggling to see how I can leverage the current time of the slider to drive my symbology.  Can anyone point me to some similar snippets that might help me achieve this?  Is it possible?

Semi related for others that might discover this issue:
[Unwinding the Clock](https://www.esri.com/arcgis-blog/products/mapping/mapping/unwinding-the-clock-visualizing-time-with-arcade/)
[Create a Time Variable for Time Enabled Data](https://community.esri.com/ideas/15975-create-a-time-variable-for-time-enabled-data) - this suggests that I might not be alone.

**Comment by ekenes** [comment]
I'm not sure this really is an Arcade issue. In the Visualization profile of the ArcGIS JS API, Arcade just returns data values that can be used as the basis for rendering, but it doesn't actually do anything to alter the visual properties of a renderer - for instance, it can't return an opacity value or a color, just a data value that can be mapped to those properties. This may be different in ArcGIS Pro though. I believe there is a way to return symbol properties using Arcade, not just data values there, but I'll have to defer to someone else who knows more about that product than myself.

> However, the above sample is web, and I believe was achieved using some JS over Arcade

This is correct. The JS is handling the animation and the the opacity updates.

> My question is how to best achieve this within ArcGIS Pro with Arcade?

I'm not sure of the answer to this. @williamscraigm might be able to point you to the right resources though.

**Comment by williamscraigm** [comment]
In ArcGIS Pro the color can be overidden with [Attribute-driven symbology](https://pro.arcgis.com/en/pro-app/help/mapping/layer-properties/attribute-driven-symbology.htm). See [this topic](https://pro.arcgis.com/en/pro-app/help/mapping/layer-properties/attribute-driven-color-in-symbology.htm) specifically for color settings.
