### ISSUE TITLE
Symbology in ArcGISPRO with Arcade

### ISSUE THREAD

**Issue by AngDemon** [Esri/arcade-expressions#34]
Hello,
Is it possible to add condition regarding color and thickness for line feature:

else if (y == "Secondary" && x < 2 && x > 0.8) {
return "Medium Fault";
return rgb(0, 7, 186);

regards,

Anzhelika

**Comment by MikeMillerGIS** [comment]
First enable - Allow symbol property connection
this will add the little icons next to the symbols
![image](https://user-images.githubusercontent.com/2707285/113904608-3b46f680-97a0-11eb-9343-7193f26d5852.png)

then write your arcade expression, such as 
```py
if ($feature.currentdevicestatus == 1)
{
   return "rgb(0,255,0)";
}
return "rgb(255,0,0)";
```
