### ISSUE TITLE
Constrain to Domain Code attribute rule not working

### ISSUE THREAD

**Issue by derrickocfa** [Esri/arcade-expressions#39]
Hello,

I'm having trouble using the Constrain to Domain Code arcade expression as an attribute rule in ArcGIS Pro v2.8.  I have copied the template expression and replaced var field with the field name in my table.  Here are my attribute rule properties:

![image](https://user-images.githubusercontent.com/17831636/123456195-6c60e700-d597-11eb-814f-daeb2530bc33.png)

I have found that with the constraint attribute rule enabled, I am still able to field calculate values that are outside of the domain associated with the field that I am trying to protect.  I have also tested with the 'Insert' trigger enabled.  When copying/pasting a feature that already contains an invalid value, however, the new feature is created successfully.  Any advice is greatly appreciated!

Thanks,
Derrick

**Comment by MikeMillerGIS** [comment]
That sample is out of date and not functional, will update it

**Comment by MikeMillerGIS** [comment]
check the updated rule, this requires 2.8 for layers with subtypes.

**Comment by derrickocfa** [comment]
Hi Mike, I really appreciate your work on updating the code.  Do you happen to have a template that does not deal with subtypes?  The feature class I want to apply the domain constraint to does not contain subtypes but does have several fields with assigned domains.  I'm unsure of how to modify the current script to bypass the assetgroup variable which seems to be used for subtype fields

Thanks,
Derrick

**Comment by MikeMillerGIS** [comment]
Take a look now, added a simpler version.  I did not test it :)

**Comment by derrickocfa** [comment]
Hey Mike, thanks for getting back to me so quickly.  Looks like the script needs 'var ' on line 68 right before 'assigned_fs'

Now, however, I'm getting the following error message: ERROR 001946: The input workspace type must be branch version.  My agency uses traditional versioning; is there any way to modify the script to incorporate this versioning type?  If not, no worries as I know this is now getting outside the scope of my original request

Thanks,
Derrick

**Comment by MikeMillerGIS** [comment]
fixed line 68,

Create the rule as a constraint rule, think batch validation might only work with branched versioning

**Comment by derrickocfa** [comment]
Thanks Mike, that did the trick!
