### ISSUE TITLE
Help with making a simple pie chart?

### ISSUE THREAD

**Issue by goldyblob** [Esri/arcade-expressions#46]
I am trying to make a pie chart with the Dashboard app on ArcGIS online, and this is my code: 

var disasters = Dictionary("thunderstorm winds", 7715, "blizzards",169, "floods", 1122, "cold", 138, "hail", 9487, "ice storm", 42, "wildfire", 7, "dense fog", 10, "heat", 18, "winter storm", 487, "drought", 53, "heavy snow", 293, "strong wind", 211, "winter weather", 73);

var disaster = FeatureSet(Text(disasters));

return disaster;

I'm not familiar with Arcade, so I do not know what I'm doing wrong. Can someone help?

**Comment by ekenes** [comment]
This question is more suited for the ArcGIS Dashboards community as this is a repo dedicated only to sharing expression templates.

https://community.esri.com/t5/arcgis-dashboards-questions/bd-p/arcgis-dashboards-questions
