### ISSUE TITLE
new to arcade-need guidance 

### ISSUE THREAD

**Issue by lrayburg** [Esri/arcade-expressions#54]
I don't even know if this is the place to reach out for help. But I am desperate

Am I able to use attribute rules and arcade expressions to populate one field when another field is populated, in the same feature.

and they have domains on them, and the feature will be shared as a service definition, and then published to online eventually.

any help is appreciated. Having a hard time navigating all this arcade lingo

**Comment by MikeMillerGIS** [comment]
Is it the same value or are you trying to get the description?

return $feature.fieldname and assign the rule to the field that will be set.

**Comment by lrayburg** [comment]
are you able to use attribute rules when publishing to online? 

i am trying to get the field to populate "yes" when another field is populated with something.

**Comment by MikeMillerGIS** [comment]
attribute rules in the feature service/gdb are not supported.  You could look at Field Maps, they have added support for arcade in the form.

**Comment by lrayburg** [comment]
Thank you

Lisa Rayburg
GIS Database Administrator
ODOT District 2
317 E. Poe Rd., Bowling Green, Ohio  43402
Cell: 419-409-0236
Office: 419-373-4378

***@***.***

**Comment by lrayburg** [comment]
Ok. Sounds good! Thanks for your help.

Also, I have never built anything in field maps, I am going to start on that process this week.



Lisa Rayburg
GIS Database Administrator
ODOT District 2
317 E. Poe Rd., Bowling Green, Ohio  43402
Cell: 419-409-0236
Office: 419-373-4378

***@***.***
