### ISSUE TITLE
Action on Arcade expression

### ISSUE THREAD

**Issue by FrankForster** [Esri/arcade-expressions#63]
Hello,

I created a data expression in ArcGIS Dashboard that return a featureset with an ID and a value.

I set an action on a selector that match property with the featureset.

The problem is that my calculated value is done with data directly from ArcGIS Online and therefore not filtered by the selector.

Is someone has already managed to set an action on a data expression ?

Thank you,

Frank

**Comment by hhkaos** [comment]
I'm sorry @FrankForster for the late response. This question is more suited for the ArcGIS Dashboards community as this is a repo dedicated only to sharing expression templates.

[community.esri.com/t5/arcgis-dashboards-questions/bd-p/arcgis-dashboards-questions](https://community.esri.com/t5/arcgis-dashboards-questions/bd-p/arcgis-dashboards-questions)
