### ISSUE TITLE
Where does JS console output go?

### ISSUE THREAD

**Issue by alex-smith-ai** [Esri/arcade-expressions#74]
Hello, I just started using arcade within the JS SDK, and I'm have a hard time finding the errors from my arcade code. My question is similar to this one about using arcade within [ArcGIS Pro](https://community.esri.com/t5/arcgis-pro-questions/where-do-the-arcade-console-messages-go-to/td-p/1057224), but for JS. The code is simple, so I'm sure I'll solve it soon, but it seems strange that I haven't seen any logs of any kind in the console. 

Thanks for the help.
Alex

**Comment by ekenes** [comment]
This question is more suited for the ArcGIS Maps SDK for JavaScript Esri Community page. Post there and you will get more visibility: https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/bd-p/arcgis-api-for-javascript-questions
